package ihm.frame;

import ihm.dialog.ErrorJOptionPane;
import interactionUser.StartWithUser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jimmy
 */
public class HomeJframe extends javax.swing.JFrame {

    
	private static final long serialVersionUID = 1L;
	private static StartWithUser SWU = new StartWithUser();
	private boolean notfirstTraceroute = false;
	
	/**
     * Creates new form Home
     */
    public HomeJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        servicejLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        listeTrjTextField = new javax.swing.JTextField();
        AddTraceroutejButton = new javax.swing.JButton();
        nbTrSimultanejTextField = new javax.swing.JTextField();
        NbSimultaneejLabel = new javax.swing.JLabel();
        ipjLabel = new javax.swing.JLabel();
        randomIpjLabel = new javax.swing.JLabel();
        randomIpjTextField = new javax.swing.JTextField();
        RandomIpjButton = new javax.swing.JButton();
        terminatedjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StatsjButton = new javax.swing.JButton();
        ExportjButton = new javax.swing.JButton();
        ImportjButton = new javax.swing.JButton();
        endNotejTextField = new javax.swing.JTextField();
        servicejComboBox = new javax.swing.JComboBox();
        NbHopsjLabel = new javax.swing.JLabel();
        NbHopsjTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        servicejLabel.setText("Service");

        listeTrjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeTrjTextFieldActionPerformed(evt);
            }
        });

        AddTraceroutejButton.setText("Ajouter");
        AddTraceroutejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTraceroutejButtonActionPerformed(evt);
            }
        });

        nbTrSimultanejTextField.setText("5");

        NbSimultaneejLabel.setText("Nb Traceroute sim.");

        ipjLabel.setText("Ip ou Nom");

        randomIpjLabel.setText("Ip aleatoire");

        RandomIpjButton.setText("Lancer");
        RandomIpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomIpjButtonActionPerformed(evt);
            }
        });

        terminatedjButton.setText("Terminer ");
        terminatedjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminatedjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(terminatedjButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(randomIpjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(randomIpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NbSimultaneejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ipjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(listeTrjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nbTrSimultanejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddTraceroutejButton)
                        .addGap(94, 94, 94))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RandomIpjButton)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbTrSimultanejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbSimultaneejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(listeTrjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(AddTraceroutejButton)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomIpjLabel)
                    .addComponent(randomIpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RandomIpjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(terminatedjButton)
                .addContainerGap())
        );

        StatsjButton.setText("Statistiques");

        ExportjButton.setText("Exporter");

        ImportjButton.setText("Importer");
        ImportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImportjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExportjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ImportjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExportjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StatsjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        endNotejTextField.setEditable(false);
        endNotejTextField.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        endNotejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endNotejTextField.setText("Corentin DUPAYS & Jimmy PADONOU");
        endNotejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endNotejTextFieldActionPerformed(evt);
            }
        });

        servicejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GeoIp", "HostIp" }));
        servicejComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                servicejComboBoxPropertyChange(evt);
            }
        });
        
        NbHopsjLabel.setText("Nb sauts max");

        NbHopsjTextField.setText("30");
        NbHopsjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbHopsjTextFieldActionPerformed(evt);
            }
        });

        filejMenu.setText("Fichier");

        saveMenuItem.setText("Enregistrer tout ");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(saveMenuItem);

        closeMenuItem.setText("Fermer");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(closeMenuItem);

        jMenuBar1.add(filejMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(servicejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(servicejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(NbHopsjLabel)
                        .addGap(31, 31, 31)
                        .addComponent(NbHopsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(endNotejTextField)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicejLabel)
                    .addComponent(servicejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbHopsjLabel)
                    .addComponent(NbHopsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endNotejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();    }// </editor-fold>                        

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	System.exit(0);
    }                                             

    private void endNotejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void listeTrjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void ImportjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void servicejComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {                                                
        // TODO add your handling code here:
    } 
    
    private boolean checkValueIpOrName(String Value){
    	if (!(Value.equals(""))
				||SWU.checkValue(Value)){
			return true;
		}else{
			new ErrorJOptionPane("Erreur", "Valeur saisie incorrecte. \n Impossible de lancer le traceroute ");
			return false;
		}
    }
    
    private boolean checkParameters(){
    	try {
			int nbTrSimul = Integer.parseInt(nbTrSimultanejTextField.getText());
			try {
    			int nbHops = Integer.parseInt(NbHopsjTextField.getText());
    			SWU.setNbHOPS(nbHops);
    			SWU.setNbExecSameTime(nbTrSimul);
    			return true;
    		}catch(Exception e){
    			new ErrorJOptionPane("Erreur", "La valeur du champ Nb de sauts max doit etre un entier ");
    			notfirstTraceroute = false;
    			return false;
    		}
		}catch(Exception e){
			new ErrorJOptionPane("Erreur","La valeur du champ Nb traceroute sim doit etre un entier ");
			notfirstTraceroute = false;
			return false;
		}
    }

    private void AddTraceroutejButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    	if (!notfirstTraceroute){
    		if (checkParameters()){
    			if (checkValueIpOrName(listeTrjTextField.getText())){
    				notfirstTraceroute = true;
    				nbTrSimultanejTextField.setEditable(false);
    				NbHopsjTextField.setEditable(false);
    				SWU.addTrIntoGraph(listeTrjTextField.getText());
    			}
    		}
    	}else{
    		if (checkValueIpOrName(listeTrjTextField.getText()))
				SWU.addTrIntoGraph(listeTrjTextField.getText());
    	}
    	
    }                                                    

    private void RandomIpjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    	if (!notfirstTraceroute){
    		if (checkParameters()){
    			randomIpjTextField.setText(SWU.generateRandomIp());
    			if (checkValueIpOrName(randomIpjTextField.getText()))
    				SWU.addTrIntoGraph(randomIpjTextField.getText());
    		}
    	}else{
    		if (checkValueIpOrName(randomIpjTextField.getText()))
    			SWU.addTrIntoGraph(randomIpjTextField.getText());
    	}
    }                                               

    private void terminatedjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	SWU.TerminateExecution();
    }
    
    private void NbHopsjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddTraceroutejButton;
    private javax.swing.JButton ExportjButton;
    private javax.swing.JButton ImportjButton;
    private javax.swing.JLabel NbHopsjLabel;
    private javax.swing.JTextField NbHopsjTextField;
    private javax.swing.JLabel NbSimultaneejLabel;
    private javax.swing.JButton RandomIpjButton;
    private javax.swing.JButton StatsjButton;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JTextField endNotejTextField;
    private javax.swing.JMenu filejMenu;
    private javax.swing.JLabel ipjLabel;
    private javax.swing.JLabel servicejLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField listeTrjTextField;
    private javax.swing.JTextField nbTrSimultanejTextField;
    private javax.swing.JLabel randomIpjLabel;
    private javax.swing.JTextField randomIpjTextField;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JComboBox servicejComboBox;
    private javax.swing.JButton terminatedjButton;
    // End of variables declaration   
    // End of variables declaration                   
}
